### ISSUE TITLE
Add Game Piece Tracking

### ISSUE THREAD

**Issue by JosephTLockwood** [Hemlock5712/2025SwerveTemplate#17]
This has been started on request #9 

The following will be needed to implement game piece tracking.

- [ ] Easy way to find the distance to the game piece (this will need to use pose `sampleAt()`, not current pose)
- [ ] Implement Orbit formula to guide to game piece
- [ ] Implement PID so you can tune aggressiveness
- [ ] Add an example of how to add to Auto with PathPlanner overrides.

**Comment by JosephTLockwood** [comment]
I will leave the branch as a starting point to implement, but due to game piece complications, this is probably outside the template's scope.
